### ISSUE TITLE
Air transports ram freshly unloaded units across the map (#10)

### ISSUE THREAD

**Issue by CommanderSpice** [CommanderSpice/Phoenix-Annihilation#12]
This is an engine issue.
Making airplanes unable to collide with any mobile units (not just other airplanes #5) might be a viable workaround for this.
Side effects would be:
- Airplanes which are inside the model of a bigger unit are invisible
- Airplanes which are in the collision volume of a bigger unit are invincible
Any other?

**Comment by silentwings** [comment]
Collision with (mobile) units won't make any difference afaik.

I think all you can really do here is make a replay of the problem and give it to the engine devs.

**Comment by CommanderSpice** [comment]
Should be fixed with c11b1a488e508fb44a8e958303af1b29dfbb0dd6.
